#!/bin/bash
set -euo pipefail
help() { echo "run, the minimalist's task runner - https://github.com/simpzan/run"; }

teardown() {
  make clean
  rm -rf .stardict
}
setup() {
  make
  mkdir -p .stardict/dic/
  cp stardict-Collins_Cobuild_5-2.4.2/* .stardict/dic/
  gzip -d -k -f -S dz .stardict/dic/Collins_Cobuild_5.dict.dz
  mv .stardict/dic/Collins_Cobuild_5.dict. .stardict/dic/Collins_Cobuild_5.dict
  lookup apple
}
lookup() {
  LD_LIBRARY_PATH=`pwd` HOME=`pwd` ./sd-cmd $@
}

main_() {
  if [[ -z "$@" ]]; then
    compgen -A function | grep -v "_$"
  elif declare -F "$1" >/dev/null; then
    "$@"
  else
    echo "Error: unknown function '$1'" >&2
  fi
}
main_ $@
